### ISSUE TITLE
VKD3D is not correctly recognized in the general settings

### ISSUE THREAD

**Issue by Knebergish** [bottlesdevs/components#100]
If I go to the components installation tab in Bottles general settings and install vkd3d-v2.5, then after restarting Bottles in the same settings window this component will be marked as not installed. All files exist in the filesystem and in bottle specific settings this vkd3d can be used (but with name "vkd3d-proton-2.5"). And when running Bottles, the logs show that this vkd3d is detected. Only its status is incorrectly displayed in the general settings window.

Perhaps this problem is related to #92 .

![vkd3d](https://user-images.githubusercontent.com/10116459/151563488-71993580-c202-4e0a-bcc6-664cd0308d8a.png)

**Comment by mirkobrombin** [comment]
Thanks for reporting, I’ll make a patch

**Comment by mirkobrombin** [comment]
Fixed in repository, no need to upgrade Bottles.
