### ISSUE TITLE
[Request] Support for DXVK async patch

### ISSUE THREAD

**Issue by Danacus** [bottlesdevs/components#107]
**Is your feature request related to a problem? Please describe.**
Some games perform poorly with default DXVK (e.g. some UE4 games). [dxvk-async](https://github.com/Sporif/dxvk-async) solves this problem, but is not supported by Bottles from what I can tell.

**Describe the solution you'd like**
Add an option to install DXVK with async patch.

**Describe alternatives you've considered**
As a workaround, I assume it's possible to install dxvk-async next to the executable and add a DLL override.

**Comment by mirkobrombin** [comment]
Moved to the right repository. 

It’s “just” a dxvk variant so adding it to the components repository should be enough.

**Comment by EvoXCX** [comment]
DXVK Async not listed in DXVK/VK3D installer tab but is it in index.yml
