### ISSUE TITLE
Runtime always has an update

### ISSUE THREAD

**Issue by Knebergish** [bottlesdevs/components#109]
On new "Core" settings tab, runtime-0.2 always has an update. After applying the update and restarting Bottles, the update appears again.
It looks a little like #100

**Comment by mirkobrombin** [comment]
I thought I fixed it, maybe it is reading the wrong index from the components repository. Let me check

**Comment by mirkobrombin** [comment]
Fixed, btw runtime installation require Bottles restart. Can you try again in a few minutes?

**Comment by Knebergish** [comment]
Updated to runtime-0.3, the problem is gone, thank you.
