### ISSUE TITLE
Add Proton-7.4

### ISSUE THREAD

**Issue by tiziodcaio** [bottlesdevs/components#115]
Please add proton 7.4 as it is relased

**Comment by mirkobrombin** [comment]
We provide Proton-GE, not Proton. Also there is an important thing to consider: GloriousEggroll switched from Proton-GE to GE-Proton which is not "just a name". Latest Proton-GE release is 7.3, while latest GE-Proton is 7.4.

We need to test if the new GE-Proton builds works on Bottles like the old Proton-GE works before.

**Comment by tiziodcaio** [comment]
If you are working on it i close the issue

**Comment by mirkobrombin** [comment]
I’ll keep this open as a reference

**Comment by mirkobrombin** [comment]
Now available
