### ISSUE TITLE
[Request]: Adding Lutris-GE-LoL versions as Runners

### ISSUE THREAD

**Issue by VihagChaturvedi** [bottlesdevs/components#125]
### Tell us the problem or your need

Lutris currently provides LoL Support, from the seems of it, Bottles doesn't seem to ship them by default.

### Describe the solution you'd like

Would love to have the Runners added to Bottles, as it isn't possible to manually add for Flatpaks

Here is the GH for further reference: https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.0-GE-1-LoL

**Comment by mirkobrombin** [comment]
We already provide the -lol runner https://github.com/bottlesdevs/components/blob/main/runners/wine/lutris-ge-7.0-GE-1-LoL.yml

Btw this is disabled by default with Flatpak as it can't works under flatpak: https://github.com/flathub/net.lutris.Lutris/issues/85
