### ISSUE TITLE
Add vanilla-cx 21.2.0

### ISSUE THREAD

**Issue by tiziodcaio** [bottlesdevs/components#126]
https://media.codeweavers.com/pub/crossover/source/crossover-sources-21.2.0.tar.gz

**Comment by mirkobrombin** [comment]
Each build take some hours. I had very few successes with this runner, are you sure it's necessary?

**Comment by tiziodcaio** [comment]
No don't worry... If is necessary i can do it

**Comment by tiziodcaio** [comment]
https://mega.nz/file/actyhTjB#zwzJrABQApBfEMhlHig42HbDHOvY2HxrUT9xF6MQTc0

**Comment by tiziodcaio** [comment]
https://mega.nz/file/CM9HSJAY#qN4AWo9Jy53ozA0-2L-QNhqe28P7qsHRybKoBJv7Y6E

**Comment by mirkobrombin** [comment]
No wait, I explained myself badly. Builds take hours but for me it's just a click. Vaniglia should be  built in clean environment with dependencies at the specific  version. What I meant is: is this release necessary? I had very few results with cx but I can run the build if you have explicitly need of this. 


If this is for office: the only differences between caffe and cx (in this case) is that cx came with some dependencies that can be installed through  our GUI. If you are trying with the ISOs I’ve posted in the other issues: those fails with cx too.

**Comment by mirkobrombin** [comment]
building https://github.com/bottlesdevs/wine/actions/runs/2188407711

**Comment by mirkobrombin** [comment]
https://github.com/bottlesdevs/wine/releases/tag/21.2.0-cx
