### ISSUE TITLE
First run error: "Source cksum of caffe-7.6 looks corrupted"

### ISSUE THREAD

**Issue by AshmuneinStork** [bottlesdevs/components#127]
Hello!

I tried installing your application on a freshly installed fedora 35 workstation.

When installing the required components of the first run in the terminal, the following error pops up and goes into a cyclic process.

Sorry for the english, I use google translate.

`````
WARNING No runners found. 
INFO Installing component: [caffe-7.6]. 
Downloading caffe-7.6-x86_64.tar.xz: 100% [==================================================>

INFO Renaming [caffe-7.6-x86_64.tar.xz] to [caffe-7.6-x86_64.tar.xz]. 
ERROR Downloaded file [caffe-7.6-x86_64.tar.xz] looks corrupted. 
ERROR Source cksum: [9050f43bcb320fccba3b1dd9a25b9ac8] downloaded: [bcbcc047e908f75af1c8032ae492d487] 
INFO Removing corrupted file [caffe-7.6-x86_64.tar.xz]. 
ERROR Extraction failed! Archive ends earlier than expected. 
INFO Runners found:
	 - sys-wine-7.5
 
WARNING No runners found. 
`````

**Comment by Oreeeee** [comment]
#128

**Comment by JohnMansell** [comment]
Experiencing the same bug. Also Fedora 35.
```
WARNING No runners found. 
INFO Installing component: [caffe-7.6]. 
Downloading caffe-7.6-x86_64.tar.xz: 100% [==================================================>

INFO Renaming [caffe-7.6-x86_64.tar.xz] to [caffe-7.6-x86_64.tar.xz]. 
ERROR Downloaded file [caffe-7.6-x86_64.tar.xz] looks corrupted. 
ERROR Source cksum: [9050f43bcb320fccba3b1dd9a25b9ac8] downloaded: [bcbcc047e908f75af1c8032ae492d487] 
INFO Removing corrupted file [caffe-7.6-x86_64.tar.xz]. 
ERROR Extraction failed! Archive ends earlier than expected. 
INFO Runners found:
	 - sys-wine-7.0
```

Also, it was frustrating that I only see this if I run the flatpak from the command line to see the output when downloading. The GUI, which is the method used in the guide, shows nothing. It just sits there endlessly while Caffe-7.6 tries to re-download infinite times. No useful output of information on why it is in an endless loop.

**Comment by Oreeeee** [comment]
>It just sits there endlessly while Caffe-7.6 tries to re-download infinite times. No useful output of information on why it is in an endless loop.

Bottles is trying to redownload this file until the checksum matches, but obviously checksum isn't gonna match when checksum on the server is miscalculated. There should be a argument to skip checksums when this happens.

**Comment by Tennyleaz** [comment]
A temporary solution is to disconnect my internet before launching bottles. Bottles would skip downloading caffe-7.6.

**Comment by AshmuneinStork** [comment]
> #128

Thank you very much!

Now the installation is working correctly!
