### ISSUE TITLE
Wine Builds

### ISSUE THREAD

**Issue by trymeouteh** [bottlesdevs/components#133]
Please create a repository of original wine builds from wine-mirror github repository that are not modified in any way unlike the Vaniglia builds.

Vaniglia is a [modified version](https://docs.usebottles.com/components/runners) of the original Wine runners. Having the original Wine runner would allow users to ensure their Windows software and games do work in Wine if they decided to stop using Bottles or use a different runner manger like Lutris, PlayOnLinux, etc.

https://github.com/wine-mirror/wine

**Comment by mirkobrombin** [comment]
Thank you for reaching us.

Providing "pure" wine builds is a very time-consuming task. Each build takes ~2 hours, this should be tested and then published and we are already busy with other tasks. Feel free to keep a pure wine repository on your own.

**Comment by StoneMoe** [comment]
Looking forward to stock wine(-staging) too, Input method is completely broken in soda and caffe, and developer from fcitx says it might be an issue with patched wine.
