### ISSUE TITLE
Proton Builds

### ISSUE THREAD

**Issue by trymeouteh** [bottlesdevs/components#134]
Please create a repository of original proton builds from the ValveSoftware/Proton github repository that are not modified in any way unlike Proton-GE builds.

[Vaniglia is a forked repository of wine](https://github.com/bottlesdevs/wine). By forking the ValveSoftware/Proton github repository, proton runners can be made available to download and run in Bottles. Having the original Proton runner would allow users to ensure their Windows games do work in Proton if they decided to stop using Bottles or use a different runner manger like Steam.

https://github.com/ValveSoftware/Proton

**Comment by mirkobrombin** [comment]
Same as https://github.com/bottlesdevs/components/issues/133
