### ISSUE TITLE
Using a patched runner for w3champions + warcraft 3

### ISSUE THREAD

**Issue by bpmooch** [bottlesdevs/components#139]
[wc3champions](https://w3champions.com/) is a cool game specific thing that required a [patched runner](https://github.com/kostile/wine/releases/tag/wine-ge-proton-6.19-wc3-minimap) to work. I'm trying to figure out how to test the runner using bottles. Pull request for testing the runner is here https://github.com/bottlesdevs/components/pull/138

**Comment by mirkobrombin** [comment]
To test the runner, just place it in your `runners` folder

**Comment by mirkobrombin** [comment]
Merged, it should be available in Bottles under "Other runners" in minutes.

**Comment by bpmooch** [comment]
> To test the runner, just place it in your `runners` folder

thank for this, had no idea
