### ISSUE TITLE
Does the "soda" runner support futex2?

### ISSUE THREAD

**Issue by m911t** [bottlesdevs/components#148]
Asking because I'm confused if ANY runner supports it or not. The terminal says "using server side synchronization" while using esync or fsync says "e/fsync: enabled"

**Comment by mirkobrombin** [comment]
Your distro kernel must support it (5.16 if I’m not wrong)

**Comment by m911t** [comment]
IIRC it landed on 5.15 and I'm on 5.18 on Arch (and also fedora but fedora behaved the same way)

**Comment by mirkobrombin** [comment]
So you should be using futex2. Wine logs are just weird

**Comment by m911t** [comment]
ah, thanks then.
