### ISSUE TITLE
Add new Lutris-GE-LoL build

### ISSUE THREAD

**Issue by kassindornelles** [bottlesdevs/components#156]
this build doesnt needs any system wide change like the vsyscall32 one, is fixed now so i guess it fits inside bottles

Build link:
https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.0-GE-3-LoL

GE explained the new build:
https://www.reddit.com/r/leagueoflinux/comments/w97wr4/lutrisge703lol_released_fixes_abivsyscall320/

UPDATE:
new build fixes garena
https://www.reddit.com/r/leagueoflinux/comments/w9nz5s/lutrisge704lol_released_fixes_garena_fixes_direct/

github:
https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.0-GE-4-LoL

**Comment by TheNamelessWonderer** [comment]
Pretty sure it still doesn't run in flatpak because of https://github.com/flathub/net.lutris.Lutris/issues/85

**Comment by SuNNjek** [comment]
Just tried it, still needs `modify_ldt` unfortunately so it doesn't work

**Comment by GustavoPeredo** [comment]
It still needs the patch for the flatpak version, but other versions should work fine. Also, if using NixOS you can use my configuration to fix the issue.

```
{ config, pkgs, ... }:
let 
lol = builtins.toFile "lol" ''
          --- a/common/flatpak-run.c    2022-08-06 17:22:32.275764357 +0200
          +++ b/common/flatpak-run.c    2022-08-06 17:22:55.071886221 +0200
          @@ -3113,9 +3113,6 @@
               {SCMP_SYS (uselib), EPERM},
               /* Don't allow disabling accounting */
               {SCMP_SYS (acct), EPERM},
          -    /* 16-bit code is unnecessary in the sandbox, and modify_ldt is a
          -       historic source of interesting information leaks. */
          -    {SCMP_SYS (modify_ldt), EPERM},
               /* Don't allow reading current quota use */
               {SCMP_SYS (quotactl), EPERM},
 


        '';
in
{
  imports =
    [ 
      ./hardware-configuration.nix
    ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  networking.hostName = "nixos"; # Define your hostname.


  networking.networkmanager.enable = true;

  services.xserver.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.opengl.enable = true;

  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable;

  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;

  services.xserver = {
    layout = "us";
    xkbVariant = "alt-intl";
  };

  services.printing.enable = true;

  sound.enable = true;
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  nixpkgs.overlays = [ (
    self: super:
    {
      flatpak = super.flatpak.overrideAttrs (old: {
        patches = (old.patches or []) ++ [
          "${lol}"
        ];
      });
    }
  )];

  users.users.gustavo = {
    isNormalUser = true;
    description = "Gustavo Peredo";
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [
      firefox
      flatpak
    ];
  };

  nixpkgs.config.allowUnfree = true;
  
  services.flatpak.enable = true;

  environment.systemPackages = with pkgs; [
    gnomeExtensions.appindicator
    gnomeExtensions.pop-shell
    vim
  ];
  system.stateVersion = "22.05"; 

}
```

Also, the newest version was merged for hackers and non flatpak users ;) https://github.com/bottlesdevs/components/pull/159

**Comment by mirkobrombin** [comment]
Nice

**Comment by SuNNjek** [comment]
For all the Arch users out there (like me :smile:) I created an AUR package that removes the `modify_ldt` restriction with the patch by @GustavoPeredo here: https://aur.archlinux.org/packages/flatpak-lol

**Comment by kassindornelles** [comment]
> For all the Arch users out there (like me smile) I created an AUR package that removes the `modify_ldt` restriction with the patch by @GustavoPeredo here: https://aur.archlinux.org/packages/flatpak-lol

this is awful but i love it

**Comment by kassindornelles** [comment]
not a bottles issue, closing since now i know it
