### ISSUE TITLE
Caffe runner update

### ISSUE THREAD

**Issue by MrQuerter** [bottlesdevs/components#160]
Hi. Was the Caffe runner dropped? It's on 7.10 while Wine released 7.15 two days ago. If not, can I know the schedule that is now used for this runner? I like it more than the Soda.

**Comment by mirkobrombin** [comment]
Currently building

**Comment by MrQuerter** [comment]
When can we expect it?

**Comment by mirkobrombin** [comment]
There are problems building it, I'll retry soon
