### ISSUE TITLE
Please expose the wine-wayland runner

### ISSUE THREAD

**Issue by adworacz** [bottlesdevs/components#162]
I see that there's already a reference to `wine-wayland` in the `runners` directory, but it's not accessible when I load up Bottles. I'm assuming this is because it's missing from the `index`?

I might be missing some kind of workaround though.

## Context
I'm trying to run Bottles on Sway, a Wayland compositor based on wlroots.

**Comment by mirkobrombin** [comment]
Sorry, that runner is not compatible with Bottles. Btw, any runner already works on wayland as it run in xwayland
