### ISSUE TITLE
vaniglia-7.15 runner seems to be bugged, can't launch anything

### ISSUE THREAD

**Issue by slowpokefarm** [bottlesdevs/components#163]
When I switch runner to vaniglia-7.15 I can't launch anything in the bottle and get the following error:
```
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
0070:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
wine client error:0: version mismatch 756/739.
Your wine binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
```

**Comment by mirkobrombin** [comment]
Kill all processes and restart bottles. There is a zombie-process.

**Comment by MrQuerter** [comment]
Also have this problem. Your solution doesn't work, not even rebooting the OS. After changing to Soda it just works normally. sys-wine7.0 works too.

**Comment by mirkobrombin** [comment]
Yes I'm going to retire it, the build is broken. I'll try a new build or wait for another wine release.
