### ISSUE TITLE
Activate the CI

### ISSUE THREAD

**Issue by koplo199** [bottlesdevs/components#193]
Now that #191 and #192, is there anything left that blocks the CI from being activated?

**Comment by mirkobrombin** [comment]
the CI is active already, it's just failing https://github.com/bottlesdevs/components/actions/runs/3538533089

**Comment by koplo199** [comment]
Oh it's failing because a [ci](https://github.com/bottlesdevs/components/tree/ci) branch has been created _manually_ just before merging. The timing was so perfect I though it was an intentional (and creative) way of blocking the CI.  Just deleting this branch will solve the issue.

The branch naming prefix `ci` is reserved for the CI, but if it needs to be changed for whatever reason it could be done by editing: 
https://github.com/bottlesdevs/components/blob/2275e1953ec9799afe018a35315eb8113c3f74aa/.github/workflows/pull-components.yml#L11-L15

**Comment by mirkobrombin** [comment]
Oh this makes sense 😂

**Comment by koplo199** [comment]
Just for confirmation, has the `PAT` been set? If so, the next run should be working just fine now 🤞

**Comment by koplo199** [comment]
Seem like it [hasn't](https://github.com/bottlesdevs/components/actions/runs/3546091398/jobs/5954804036), step by step guide:
> Yay merged :tada: 
>
>Is the `PAT` already set? If it is not configured pull requests won't be created, to configure it:
>
>From any account (could very well be a newly created burner account like @bottlesdevs-components[BOT] or something) do
>`(Account) Settings -> Developer settings -> Personal access tokens -> Tokens (classic) -> Generate new token (classic) -> >public_repo (No expiration)`
>
>Then copy paste it into
>`(Repository) Settings -> Secrets -> Actions -> New repository secret -> Name = PAT`
>
_Originally posted by @koplo199 in https://github.com/bottlesdevs/components/issues/182#issuecomment-1321151903_

**Comment by mirkobrombin** [comment]
> Just for confirmation, has the `PAT` been set? If so, the next run should be working just fine now 🤞

I’ll set this asap.

**Comment by mirkobrombin** [comment]
Just a question: why not using the default GitHub bot?

**Comment by koplo199** [comment]
I've detailed the choice for this in https://github.com/bottlesdevs/Bottles/issues/2223#issuecomment-1313701226 but the tldr is that in a later date when/if auto-merge is enabled, it will be needed because the GitHub Bot cannot approve its own PR (no one can), so it needs to be done from another account

**Comment by mirkobrombin** [comment]
In retrospect it might make sense to approve them manually :thinking:

**Comment by koplo199** [comment]
> In retrospect it might make sense to approve them manually :thinking:

I agree, additionally if the idea of auto-approval is dropped then  the PAT is no longer necessary, so https://github.com/bottlesdevs/components/blob/2275e1953ec9799afe018a35315eb8113c3f74aa/.github/workflows/pull-components.yml#L251
could be replaced by `${{secrets.GITHUB_TOKEN}}` and it will work right away

**Comment by koplo199** [comment]
As the CI made its first PR #195, I guess this issue could be closed safely :+1:
