### ISSUE TITLE
vkd3d-proton 2.8 is released today, with massive performance improvements

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/components#203]
https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.8

I wanted to make a pull request but saw that you're using a separate clone of their repo to distribute this component.

Wouldn't it be better to add ZSTD support to Bottles via one of the 3 Python libraries mentioned by Facebook? See below:

http://facebook.github.io/zstd/

Then we could point directly at the official repo to simplify maintenance of Bottles.

**Comment by Bananaman** [comment]
Here's the ZSTD library list from Facebook:

Language | Author | URL
-- | -- | --
Python (full) | Gregory Szorc | https://pypi.python.org/pypi/zstandard
Python (simple) | Sergey Dryabzhinsky | https://github.com/sergey-dryabzhinsky/python-zstd
Python (bz2 api) | Ma Lin | https://pypi.org/project/pyzstd

**Comment by koplo199** [comment]
@Bananaman Yup, it is automatically handled by the CI but the last run [failed](https://github.com/bottlesdevs/components/actions/runs/3711128274/jobs/6291252552) 

#202 will fix the issue, it shouldn't happen again after that

**Comment by Bananaman** [comment]
@koplo199 Oh you're automating it, that's great! Thanks for solving it! :)
