### ISSUE TITLE
Caffe updates

### ISSUE THREAD

**Issue by Qronikarz** [bottlesdevs/components#216]
Two questions:
1. What is the update schedule of Caffe? Versions based (4 main releases since 7.20) or time based (3 months since 7.20)? 
2. Can it be automatically updated like other components (DXVK, VKD3D)? Wine releases updates very quickly (usually 2 weeks) and it would be good to have a way to test the newest version.

**Comment by superbonaci** [comment]
I'm still stuck with `overwatch2-caffe-7.18` while wine staging is already 8.7

**Comment by koplo199** [comment]
`Caffe` (and `Soda`) runners [updates are already automatically pulled](
https://github.com/bottlesdevs/components/blob/19910ff5e441d9d08ba4555f86c35174bfdf1eb1/.github/workflows/pull-components.yml#L72-L73) like `DXVK` and `vkd3d-proton`, it just... hasn't been updates.

In addition to `Vaniglia`, both of these runners are built in another repository, this is also where issues related to them are tracked: https://github.com/bottlesdevs/wine

You'll see in that repository that it also uses some kind of automation to build and release them, but it looks broken at the moment: https://github.com/bottlesdevs/wine/actions

So it seems it's a matter of willingness and time to fix the build workflow.

**Comment by superbonaci** [comment]
Thank for keeping the information updated!

**Comment by Perkolator** [comment]
I don't where I should write this, so apologies in advance.

I wanted to give feedback on Caffe runner. The last version, 7.20, is absolutely **fantastic**. I have found out that it really seems to be the only runner that works perfectly when MangoHud is ON for games that use gstreamer (and possibly with some Unity games, or some other system to show game cinematics).

I usually first try a game with the default Soda and if the game doesn't work, I select either Kron4ek or GE Wine runner. And if the game still doesn't work, I try the Caffe 7.20. I have had many games already that do not work properly when MangoHud is ON; e.g. FPS is severely dropped, cinematics do not work at all, or cinematics have only sound, or MangoHud disappears completely when a cinematic plays (and doesn't come back when "normal" gameplay continues). Usually in these cases the console output has gstreamer errors. Every single time so far Caffe 7.20 has worked fine.

I remember that I tried older versions of other runners (that I think matched the Wine version what Caffe 7.20 has) with one game that had these problems but the game still wouldn't work ok with MangoHud ON.

I have no idea what Caffe 7.20 does differently but what it does, it does wonderfully. Thank you for this runner, without it, I wouldn't have been able to run many many games with MangoHud enabled.

I hope Caffe runner is not going to be removed as obsolete, it definitely isn't. :)

**Comment by superbonaci** [comment]
The new caffe 7.2 still doesn't appear to me in Lutris. Does it require any update or must be manually added?

**Comment by mirkobrombin** [comment]
> The new caffe 7.20 still doesn't appear to me in Lutris. Does it require any update or must be manually added?

Hi, you should ask to the Lutris team for that, they do not use our repository for runners, dxvk and stuff like that.

**Comment by Qronikarz** [comment]
Caffe is updated now randomly so questions answered.
