### ISSUE TITLE
Improved naming of new component updates?

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/components#233]
Hi! :) The current format is `<project>-<packaging revision>-<suffix aka git commit id>`, such as `dxvk-2.0-1-d020f44`.

https://github.com/bottlesdevs/components/tree/main/vkd3d
https://github.com/bottlesdevs/components/tree/main/dxvk

The naming idea is proper, but the way that the `packaging revision` is forever at `1` means it's very hard for people to know which installed component is their latest version.

Would it be possible to switch to updating the revision numbers for future component updates? Like this:

```
dxvk-2.0-1-12901b5
dxvk-2.0-2-18b0ef6
dxvk-2.0-3-196fefe
dxvk-2.0-4-7644776
dxvk-2.0-5-c55c093
dxvk-2.0-6-d020f44
dxvk-2.1 (the latest "stable")
dxvk-2.1-1-fe37bc2 (first git revision/commit after 2.1, hence start a new `-1-` sequence)
```

That way it's easy to see "6 is the latest revision, we should use that and we can delete all the other ones".

**Comment by koplo199** [comment]
This is a great idea, I'll implement it in a later revision of the CI.
