### ISSUE TITLE
Proton 6.10 GE and Lutris Wine 6.10 released

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/components#24]
- https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/6.10-GE-1
- https://github.com/lutris/wine/releases/tag/lutris-6.10

Say, how do I retrieve the checksum?

**Comment by mirkobrombin** [comment]
> * https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/6.10-GE-1
> * https://github.com/lutris/wine/releases/tag/lutris-6.10
> 
> Say, how do I retrieve the checksum?

Unfortunately they do not provide the checksum, you have to download the files and get it manually in MD5

**Comment by TheEvilSkeleton** [comment]
Awesome! That's all I needed. I'll MR soon.
