### ISSUE TITLE
Request for ability to run command on host system before executing in bottle.

### ISSUE THREAD

**Issue by enveezee** [bottlesdevs/components#282]
Bottles is often used for and geared toward gaming type applications. In linux there are things like antimicroX which allow custom profiles to be applied to joysticks to allow joysticks to function on games and things not meant for such stuff. The use case here would be to run something like antimicrox --profile-controller 0 mygame --profile-controller 1 mygame on the host OS prior to loading a game, so that when you launch the game, the appropriate controller profiles are also loaded automatically.

**Comment by koplo199** [comment]
This is issue belongs to the [Bottles](https://github.com/bottlesdevs/bottles/) repository.

Note: This is possible already with [gamemode.ini](https://github.com/FeralInteractive/gamemode/blob/1f28880509ad6ac619c58633a2d0c79f78ebe30a/example/gamemode.ini#L88-L97) custom scripts. You could have one config file per game in each game directory, and/or a globally applied config as explained in the [README](https://github.com/FeralInteractive/gamemode#configuration). For your use case, I doubt antimicrox is available as a flatpak, so you would have to give Bottles full access to the filesystem with `--filesystem=host` to be able to execute it. This will likely never be the default, so if this is what you're asking don't bother open an issue on the Bottles repostory.

**Comment by orowith2os** [comment]
When you set up a gamemode script, it should execute everything on the host, so this is unnecessary in the first place, and it should've been made in the Bottles repository, not the Components repository.
