### ISSUE TITLE
Please, add Wine-GE runner

### ISSUE THREAD

**Issue by SoongVilda** [bottlesdevs/components#73]
Hello, I think it would be great to add Wine-GE as runner. Wine-GE contain a lot of  useful patches, it can help and makes gaming more easier.

https://github.com/GloriousEggroll/wine-ge-custom

**Comment by mirkobrombin** [comment]
I thought `wine-ge` and `wine-lutris-ge` were different runners but apparently not. We [already offer](https://github.com/bottlesdevs/components/blob/main/runners/wine/lutris-ge-6.20-1.yml) `wine-ge` in our component repository, under the name `wine-lutris-ge`.

I see that it is under our `unstable` channel but I think this is simply a mistake 😅 I will move it under `stable` channel so you can start using from inside Bottles without need to enable the RC/Unstable flag.
