### ISSUE TITLE
Please, add Wine-tkg runner (Because of FUTEX2)

### ISSUE THREAD

**Issue by SoongVilda** [bottlesdevs/components#74]
Wine-tkg can be also useful, because that version can use new FUTEX2 (better than esync or fsync)

https://github.com/Frogging-Family/wine-tkg-git

Mainline kernel still don't have FUTEX2, but linux-zen on Arch Linux have latest FUTEX2 pacthes. So many people can have much better gaming expericnes with wine-tkg on linux-zen.

**Comment by mirkobrombin** [comment]
Published, will be available soon.

FYK there is a bug in current release that breaks the "Browse files" in Runners preferences. This is already fixed in the upcoming new release 2021.11.14 https://github.com/bottlesdevs/Bottles/issues/675
