### ISSUE TITLE
Mass Effect Legendary Edition has no selection menu

### ISSUE THREAD

**Issue by MichelN86** [bottlesdevs/components#98]
This is a issue because D3D Extra is not added in bottles. When i turn this one off in Lutris i don't have the menu either, when i enable it i get the screen where i can select my 3 games.

[D3D Extra should be added](https://github.com/lutris/d3d_extras/releases/tag/v2), Lutris added this a few months ago and fixed this game

Turned off:
![Schermafdruk van 2022-01-18 11-51-48](https://user-images.githubusercontent.com/97549636/149924031-9725fbb7-0e7a-41ec-aca3-5cf46da2b64a.png)
![Schermafdruk van 2022-01-18 11-51-33](https://user-images.githubusercontent.com/97549636/149924024-4e50e44b-4fc8-44cd-aa45-40363fc6a1d3.png)

Turned on:
![Schermafdruk van 2022-01-18 11-55-23](https://user-images.githubusercontent.com/97549636/149924249-67e41350-3aa1-4078-ada6-369cda568166.png)
![Schermafdruk van 2022-01-18 11-52-03](https://user-images.githubusercontent.com/97549636/149924369-f044c948-268e-4f92-bdf9-3853fdd02b04.png).

**Comment by mirkobrombin** [comment]
D3D extras are just…. DLLs from the directx9 package? So you can just install our directx9 dependency. Let me know if I’m wrong.

**Comment by MichelN86** [comment]
I tried to install directx 9 in lutris before and in bottles and that never
fixed it for me. Not sure what these are but all i know is that this fixed
the game.


Op di 18 jan. 2022 12:14 schreef Mirko Brombin ***@***.***>:

**Comment by mirkobrombin** [comment]
I’ll investigate but seems like just a bunch of directx dlls. I need to know how are these provided to trust the source.

**Comment by MichelN86** [comment]
I did some testings in bottles again, i manually installed directx + vredist 2019 from the Mass Effect Legendary Edition folder using bottles. It seems the menu does appear right now. I wonder why it did not appear earlier.

**Comment by mirkobrombin** [comment]
There is an hotfix that should fix d3dx9 and d3dcompiler

**Comment by MichelN86** [comment]
You mean the last released version ? that one i installed today. Maybe that is why it is working.

**Comment by mirkobrombin** [comment]
Yup. I’ll close this issue
